version: "3.9"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    networks:
      - smartcare-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - patient-service
      - doctor-service
      - appointment-service
      - payment-service
      - notification-service
      - telemedicine-service
    environment:
      - PORT=5000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:5001
      - AUTH_SERVICE_URL=http://auth-service:5002
      - DOCTOR_SERVICE_URL=http://doctor-service:5003
      - NOTIFICATION_SERVICE_URL=http://notification-service:5004
      - PATIENT_SERVICE_URL=http://patient-service:5005
      - PAYMENT_SERVICE_URL=http://payment-service:5006
      - TELEMEDICINE_SERVICE_URL=http://telemedicine-service:5007
    networks:
      - smartcare-net

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://auth-db:27017/authdb
      - JWT_SECRET=secret
    depends_on:
      - auth-db
    networks:
      - smartcare-net

  patient-service:
    build: ./services/patient-service
    container_name: patient-service
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://patient-db:27017/patientdb
      - JWT_SECRET=secret
    depends_on:
      - patient-db
    networks:
      - smartcare-net

  doctor-service:
    build: ./services/doctor-service
    container_name: doctor-service
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://doctor-db:27017/doctordb
      - JWT_SECRET=secret
      - AUTH_SERVICE_URL=http://auth-service:5001
      - INTERNAL_SERVICE_SECRET=secret
    depends_on:
      - doctor-db
    networks:
      - smartcare-net

  appointment-service:
    build: ./services/appointment-service
    container_name: appointment-service
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://appointment-db:27017/appointmentdb
      - JWT_SECRET=secret
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PATIENT_SERVICE_URL=http://patient-service:5002
      - DOCTOR_SERVICE_URL=http://doctor-service:5003
      - TELEMEDICINE_SERVICE_URL=http://telemedicine-service:5007
      - INTERNAL_SERVICE_SECRET=secret
    depends_on:
      - appointment-db
    networks:
      - smartcare-net

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://payment-db:27017/paymentdb
      - JWT_SECRET=secret
    depends_on:
      - payment-db
    networks:
      - smartcare-net

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    environment:
      - PORT=5006
      - JWT_SECRET=secret
    networks:
      - smartcare-net

  telemedicine-service:
    build: ./services/telemedicine-service
    container_name: telemedicine-service
    environment:
      - PORT=5007
      - JWT_SECRET=secret
    networks:
      - smartcare-net

  # MongoDB Containers (internal only)

  auth-db:
    image: mongo:7
    container_name: auth-db
    volumes:
      - auth_data:/data/db
    networks:
      - smartcare-net

  patient-db:
    image: mongo:7
    container_name: patient-db
    volumes:
      - patient_data:/data/db
    networks:
      - smartcare-net

  doctor-db:
    image: mongo:7
    container_name: doctor-db
    volumes:
      - doctor_data:/data/db
    networks:
      - smartcare-net

  appointment-db:
    image: mongo:7
    container_name: appointment-db
    volumes:
      - appointment_data:/data/db
    networks:
      - smartcare-net

  payment-db:
    image: mongo:7
    container_name: payment-db
    volumes:
      - payment_data:/data/db
    networks:
      - smartcare-net

networks:
  smartcare-net:
    driver: bridge

volumes:
  auth_data:
  patient_data:
  doctor_data:
  appointment_data:
  payment_data: